"""FASHN provider adapter.

The adapter owns everything the application knows about the FASHN
virtual try-on API. Callers (``TryOnService``) hand it two images and a
category and receive a :class:`FashnResult` with the generated bytes —
no knowledge of HTTP, polling, or provider response shapes leaks out.

The adapter is split into small pure helpers so the parts that touch
the network are easy to isolate in tests:

* :meth:`build_payload`          — pure request body builder.
* :meth:`_normalize_category`    — pure mapping from free-form
  wardrobe categories to FASHN's closed vocabulary.
* :meth:`extract_run_id`         — pure parser for the ``POST /v1/run``
  submit response.
* :meth:`extract_status_payload` — pure parser for the ``GET /v1/status/{id}``
  poll response; returns a :class:`_StatusPayload` structured result.
* :meth:`generate_tryon`         — the only method that touches the
  network. It composes the pure helpers around a submit + polling loop
  + result image fetch.

# --- PROVIDER CONTRACT (FASHN virtual try-on v1.6) ------------------
# Submit   : POST  {base_url}/v1/run
# Auth     : "Authorization: Bearer {api_key}"
# Body     : {
#              "model_name": "tryon-v1.6",
#              "inputs": {
#                "model_image":   <url or data URI>,
#                "garment_image": <url or data URI>,
#                "category":      "auto" | "tops" | "bottoms" | "one-pieces"
#              }
#            }
# Submit response : {"id": "<prediction_id>", "error": null}
#
# Poll     : GET   {base_url}/v1/status/{prediction_id}
# Poll body:
#   {"id": "...", "status": "starting|in_queue|processing|completed|failed",
#    "output": ["https://cdn.fashn.ai/.../0.png"] | null,
#    "error": {"name": "...", "message": "..."} | null}
#
# ``model_image``/``garment_image`` accept either a publicly reachable
# HTTPS URL or a ``data:image/jpeg;base64,...`` data URI. In local dev
# MinIO is not publicly reachable, so the service layer uploads bytes
# as data URIs unconditionally.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from typing import Any, Protocol


# ---------------------------------------------------------------- constants


FASHN_MODEL_NAME = "tryon-v1.6"

#: Default generation mode. FASHN supports ``performance`` / ``balanced`` /
#: ``quality``. We default to ``quality`` because try-on is a user-facing
#: feature where visual fidelity matters more than the extra 3-5 seconds
#: of latency. Override via ``FashnAdapter(mode=...)`` when a caller
#: explicitly wants the faster modes.
FASHN_DEFAULT_MODE = "quality"

#: Terminal (non-retryable) status values returned by ``/v1/status``.
_STATUS_COMPLETED = "completed"
_STATUS_FAILED = "failed"
_TERMINAL_STATUSES = {_STATUS_COMPLETED, _STATUS_FAILED}

#: Intermediate (retryable) status values.
_RUNNING_STATUSES = {"starting", "in_queue", "processing"}

#: Categories FASHN accepts on the wire.
_FASHN_CATEGORIES = {"auto", "tops", "bottoms", "one-pieces"}

#: Pure mapping from common wardrobe category synonyms → FASHN values.
#: Extend cautiously — every unmapped value falls through to ``"auto"``,
#: which is the documented "let the model decide" default.
_CATEGORY_SYNONYMS: dict[str, str] = {
    # tops
    "top": "tops",
    "tops": "tops",
    "shirt": "tops",
    "t-shirt": "tops",
    "tshirt": "tops",
    "blouse": "tops",
    "sweater": "tops",
    "hoodie": "tops",
    "jacket": "tops",
    "coat": "tops",
    "outerwear": "tops",
    # bottoms
    "bottom": "bottoms",
    "bottoms": "bottoms",
    "pant": "bottoms",
    "pants": "bottoms",
    "trousers": "bottoms",
    "jeans": "bottoms",
    "shorts": "bottoms",
    "skirt": "bottoms",
    # one-pieces
    "dress": "one-pieces",
    "one-piece": "one-pieces",
    "onepiece": "one-pieces",
    "one-pieces": "one-pieces",
    "jumpsuit": "one-pieces",
    "romper": "one-pieces",
    "overall": "one-pieces",
    "overalls": "one-pieces",
}


# ---------------------------------------------------------------- errors


class FashnAdapterError(Exception):
    """Base class for every error raised by :class:`FashnAdapter`."""


class FashnAuthError(FashnAdapterError):
    """Provider rejected the request because of invalid credentials."""


class FashnRequestError(FashnAdapterError):
    """Provider returned a non-success status that is not auth-related."""


class FashnTimeoutError(FashnAdapterError):
    """Provider did not respond / did not finish within the configured window."""


class FashnResponseError(FashnAdapterError):
    """Provider response did not match a known supported shape."""


# ---------------------------------------------------------------- result


@dataclass(frozen=True)
class FashnResult:
    """Normalized representation of a FASHN response.

    ``image_bytes`` is the actual generated image. The adapter is the
    component that knows how to fetch them — the service consumes bytes
    and never thinks about FASHN URLs.
    """

    image_url: str
    image_bytes: bytes
    content_type: str
    provider_job_id: str | None
    raw: dict = field(default_factory=dict)


@dataclass(frozen=True)
class _StatusPayload:
    """Normalized ``GET /v1/status/{id}`` body.

    Used internally by the polling loop. Kept pure so
    :meth:`FashnAdapter.extract_status_payload` can be exhaustively
    tested without hitting the network.
    """

    status: str
    output_urls: tuple[str, ...]
    error_message: str | None
    raw: dict


# ---------------------------------------------------------------- http seam


class _AsyncHTTPClient(Protocol):
    """Minimal subset of an httpx-like async client used by the adapter."""

    async def post(
        self, url: str, *, headers: dict[str, str], json: dict[str, Any]
    ) -> Any: ...

    async def get(
        self, url: str, *, headers: dict[str, str] | None = None
    ) -> Any: ...

    async def aclose(self) -> None: ...


# ---------------------------------------------------------------- adapter


class FashnAdapter:
    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | None = None,
        http_client: _AsyncHTTPClient | None = None,
        timeout: float = 60.0,
        poll_interval: float = 2.0,
        poll_timeout: float = 180.0,
        mode: str = FASHN_DEFAULT_MODE,
    ) -> None:
        self._explicit_api_key = api_key
        self._explicit_base_url = base_url
        self._http_client = http_client
        self._timeout = timeout
        self._poll_interval = poll_interval
        self._poll_timeout = poll_timeout
        self._mode = mode

    # ----- settings -------------------------------------------------------

    @property
    def api_key(self) -> str:
        if self._explicit_api_key is not None:
            return self._explicit_api_key
        return self._load_settings_value("fashn_api_key", "")

    @property
    def base_url(self) -> str:
        if self._explicit_base_url is not None:
            return self._explicit_base_url
        return self._load_settings_value("fashn_base_url", "https://api.fashn.ai")

    @staticmethod
    def _load_settings_value(name: str, default: Any) -> Any:
        try:
            from app.core.config import settings  # lazy

            return getattr(settings, name, default)
        except Exception:
            return default

    # ----- pure helpers ---------------------------------------------------

    @staticmethod
    def _normalize_category(raw: str | None) -> str:
        """Map a free-form wardrobe category to a FASHN-accepted value.

        Returns one of ``auto`` / ``tops`` / ``bottoms`` / ``one-pieces``.
        Unknown values resolve to ``"auto"`` — the documented "let the
        model decide" default — so a new category in the wardrobe never
        breaks try-on generation.
        """
        if not raw:
            return "auto"
        key = raw.strip().lower()
        if not key:
            return "auto"
        if key in _FASHN_CATEGORIES:
            return key
        return _CATEGORY_SYNONYMS.get(key, "auto")

    def build_payload(
        self,
        *,
        person_image_url: str,
        garment_image_url: str,
        garment_category: str | None = None,
    ) -> dict[str, Any]:
        """Pure payload builder. No I/O.

        Returns the full ``POST /v1/run`` body with ``model_name`` at
        the top level and image + category fields nested under
        ``inputs``, per the FASHN v1.6 contract.
        """
        if not person_image_url:
            raise FashnRequestError("person_image_url is required")
        if not garment_image_url:
            raise FashnRequestError("garment_image_url is required")
        return {
            "model_name": FASHN_MODEL_NAME,
            "inputs": {
                "model_image": person_image_url,
                "garment_image": garment_image_url,
                "category": self._normalize_category(garment_category),
                # ``quality`` vs ``balanced`` is the single biggest
                # knob on perceived try-on quality. See
                # ``FASHN_DEFAULT_MODE`` for the rationale.
                "mode": self._mode,
            },
        }

    @staticmethod
    def extract_run_id(response_json: Any) -> str:
        """Pure parser for the ``POST /v1/run`` submit response.

        The expected body is ``{"id": "<prediction_id>", "error": null}``.
        Any other shape — or a non-null ``error`` field — raises
        :class:`FashnResponseError`.
        """
        if not isinstance(response_json, dict):
            raise FashnResponseError(
                f"expected JSON object from /v1/run, got {type(response_json).__name__}"
            )
        error = response_json.get("error")
        if error not in (None, "", {}):
            raise FashnResponseError(f"/v1/run returned error: {error!r}")
        prediction_id = response_json.get("id")
        if not isinstance(prediction_id, str) or not prediction_id:
            raise FashnResponseError(
                "/v1/run response is missing a non-empty 'id' field"
            )
        return prediction_id

    @staticmethod
    def extract_status_payload(response_json: Any) -> _StatusPayload:
        """Pure parser for the ``GET /v1/status/{id}`` body.

        Normalises the FASHN poll response into a :class:`_StatusPayload`.
        Raises :class:`FashnResponseError` on anything unexpected.
        """
        if not isinstance(response_json, dict):
            raise FashnResponseError(
                f"expected JSON object from /v1/status, got {type(response_json).__name__}"
            )

        status = response_json.get("status")
        if not isinstance(status, str) or not status:
            raise FashnResponseError(
                "/v1/status response is missing a 'status' field"
            )

        raw_output = response_json.get("output")
        output_urls: tuple[str, ...]
        if raw_output is None:
            output_urls = ()
        elif isinstance(raw_output, list):
            output_urls = tuple(
                u for u in raw_output if isinstance(u, str) and u
            )
        else:
            raise FashnResponseError(
                f"/v1/status 'output' must be a list or null, got {type(raw_output).__name__}"
            )

        raw_error = response_json.get("error")
        error_message: str | None
        if raw_error is None:
            error_message = None
        elif isinstance(raw_error, str):
            error_message = raw_error or None
        elif isinstance(raw_error, dict):
            # Shape documented as {"name": "...", "message": "..."} but
            # we render any reasonable stringification so a new error
            # sub-shape never loses its message on the way out.
            name = raw_error.get("name")
            message = raw_error.get("message")
            if name and message:
                error_message = f"{name}: {message}"
            else:
                error_message = message or name or str(raw_error)
        else:
            error_message = str(raw_error)

        return _StatusPayload(
            status=status,
            output_urls=output_urls,
            error_message=error_message,
            raw=response_json,
        )

    # ----- network --------------------------------------------------------

    async def generate_tryon(
        self,
        *,
        person_image_url: str,
        garment_image_url: str,
        garment_category: str | None = None,
    ) -> FashnResult:
        """Submit a try-on, poll until finished, and fetch the result bytes.

        Returns a :class:`FashnResult` on success. Every failure mode
        is translated to one of the typed exceptions above so
        :class:`~app.services.tryon_service.TryOnService` can map them
        to HTTP status codes without inspecting string messages.
        """
        payload = self.build_payload(
            person_image_url=person_image_url,
            garment_image_url=garment_image_url,
            garment_category=garment_category,
        )

        # Preflight credential check. httpx refuses to serialise a header
        # whose value is literally ``Bearer `` (trailing whitespace, no
        # token) and raises ``LocalProtocolError: Illegal header value``.
        # Turn that into a typed :class:`FashnAuthError` here so the
        # service layer can map it to a clean 502 with a meaningful
        # message.
        api_key = (self.api_key or "").strip()
        if not api_key:
            raise FashnAuthError(
                "FASHN API key is not configured (FASHN_API_KEY is empty). "
                "Set the key in the backend .env and restart the api service."
            )
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }

        owns_client = False
        client = self._http_client
        if client is None:
            import httpx  # lazy

            client = httpx.AsyncClient(timeout=self._timeout)
            owns_client = True

        try:
            # 1. Submit the run.
            prediction_id = await self._submit_run(client, headers, payload)

            # 2. Poll /status until completed or failed.
            status_payload = await self._poll_until_terminal(
                client, headers, prediction_id
            )

            if status_payload.status == _STATUS_FAILED:
                raise FashnRequestError(
                    f"FASHN run {prediction_id} failed: "
                    f"{status_payload.error_message or 'unknown error'}"
                )
            if status_payload.status != _STATUS_COMPLETED:
                # Defensive: _poll_until_terminal should only return on
                # a terminal state. If it doesn't, don't silently hand
                # a half-baked payload back to the service.
                raise FashnResponseError(
                    f"FASHN run {prediction_id} ended in non-terminal "
                    f"status {status_payload.status!r}"
                )

            if not status_payload.output_urls:
                raise FashnResponseError(
                    f"FASHN run {prediction_id} completed without any output URLs"
                )

            # 3. Fetch the actual bytes. The adapter owns this fetch —
            # the service layer never makes outbound HTTP calls.
            image_url = status_payload.output_urls[0]
            image_bytes, content_type = await self._fetch_result_image(
                client, image_url
            )

            return FashnResult(
                image_url=image_url,
                image_bytes=image_bytes,
                content_type=content_type,
                provider_job_id=prediction_id,
                raw=status_payload.raw,
            )
        finally:
            if owns_client:
                try:
                    await client.aclose()
                except Exception:  # pragma: no cover - best effort cleanup
                    pass

    # ----- network helpers ------------------------------------------------

    async def _submit_run(
        self,
        client: _AsyncHTTPClient,
        headers: dict[str, str],
        payload: dict[str, Any],
    ) -> str:
        try:
            response = await client.post(
                f"{self.base_url}/v1/run",
                headers=headers,
                json=payload,
            )
        except Exception as exc:  # network/timeout
            raise FashnTimeoutError(
                f"FASHN /v1/run request failed before response: "
                f"{type(exc).__name__}: {exc!r}"
            ) from exc

        self._raise_for_status(response, "/v1/run")

        try:
            response_json = response.json()
        except Exception as exc:
            raise FashnResponseError(
                f"FASHN /v1/run response was not valid JSON: {exc}"
            ) from exc

        return self.extract_run_id(response_json)

    async def _poll_until_terminal(
        self,
        client: _AsyncHTTPClient,
        headers: dict[str, str],
        prediction_id: str,
    ) -> _StatusPayload:
        url = f"{self.base_url}/v1/status/{prediction_id}"
        loop = asyncio.get_event_loop()
        started = loop.time()

        while True:
            try:
                response = await client.get(url, headers=headers)
            except Exception as exc:
                raise FashnTimeoutError(
                    f"FASHN /v1/status request failed before response: {exc}"
                ) from exc

            self._raise_for_status(response, "/v1/status")

            try:
                response_json = response.json()
            except Exception as exc:
                raise FashnResponseError(
                    f"FASHN /v1/status response was not valid JSON: {exc}"
                ) from exc

            payload = self.extract_status_payload(response_json)
            if payload.status in _TERMINAL_STATUSES:
                return payload
            if payload.status not in _RUNNING_STATUSES:
                # Surface unknown statuses rather than spinning forever.
                raise FashnResponseError(
                    f"FASHN /v1/status returned unknown status {payload.status!r}"
                )

            if loop.time() - started >= self._poll_timeout:
                raise FashnTimeoutError(
                    f"FASHN run {prediction_id} did not finish within "
                    f"{self._poll_timeout:.0f}s (last status {payload.status!r})"
                )
            await asyncio.sleep(self._poll_interval)

    async def _fetch_result_image(
        self,
        client: _AsyncHTTPClient,
        image_url: str,
    ) -> tuple[bytes, str]:
        try:
            response = await client.get(image_url)
        except Exception as exc:
            raise FashnTimeoutError(
                f"FASHN result image fetch failed: {exc}"
            ) from exc

        image_status = getattr(response, "status_code", 200)
        if image_status >= 400:
            raise FashnRequestError(
                f"FASHN result image fetch returned status {image_status}"
            )

        image_bytes = getattr(response, "content", b"") or b""
        if not image_bytes:
            raise FashnResponseError("FASHN result image was empty")

        content_type = "image/png"
        headers_obj = getattr(response, "headers", None)
        if headers_obj is not None:
            ct = headers_obj.get("content-type") or headers_obj.get("Content-Type")
            if isinstance(ct, str) and ct:
                content_type = ct.split(";")[0].strip()
        return image_bytes, content_type

    @staticmethod
    def _raise_for_status(response: Any, endpoint: str) -> None:
        """Translate raw HTTP status codes into typed adapter errors."""
        status = getattr(response, "status_code", 200)
        if status in (401, 403):
            raise FashnAuthError(
                f"FASHN auth failed on {endpoint} (status {status})"
            )
        if status >= 400:
            # Try to surface the server's error body — FASHN returns
            # ``{"error": {"name": "...", "message": "..."}}`` on 4xx.
            detail = ""
            try:
                body = response.json()
                if isinstance(body, dict) and body.get("error"):
                    err = body["error"]
                    if isinstance(err, dict):
                        detail = f": {err.get('message') or err}"
                    else:
                        detail = f": {err}"
            except Exception:
                pass
            raise FashnRequestError(
                f"FASHN {endpoint} request failed with status {status}{detail}"
            )


__all__ = [
    "FASHN_MODEL_NAME",
    "FashnAdapter",
    "FashnAdapterError",
    "FashnAuthError",
    "FashnRequestError",
    "FashnResponseError",
    "FashnResult",
    "FashnTimeoutError",
]
